# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galfitWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(671, 555)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.mainframe = QtWidgets.QFrame(Form)
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainframe)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_14 = QtWidgets.QWidget(self.mainframe)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_2.addWidget(self.widget_14, 1, 5, 1, 1)
        self.readoutframe = QtWidgets.QFrame(self.mainframe)
        self.readoutframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.readoutframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.readoutframe.setObjectName("readoutframe")
        self.readoutGridLayout = QtWidgets.QGridLayout(self.readoutframe)
        self.readoutGridLayout.setObjectName("readoutGridLayout")
        self.gridLayout_2.addWidget(self.readoutframe, 8, 0, 1, 5)
        self.widget_6 = QtWidgets.QWidget(self.mainframe)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_2.addWidget(self.widget_6, 0, 5, 1, 1)
        self.widget_16 = QtWidgets.QWidget(self.mainframe)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_2.addWidget(self.widget_16, 9, 2, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.mainframe)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_2.addWidget(self.widget_10, 4, 5, 1, 1)
        self.widget_17 = QtWidgets.QWidget(self.mainframe)
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_2.addWidget(self.widget_17, 9, 1, 1, 1)
        self.widget_15 = QtWidgets.QWidget(self.mainframe)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_2.addWidget(self.widget_15, 2, 5, 1, 1)
        self.cutouts = QtWidgets.QFrame(self.mainframe)
        self.cutouts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cutouts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cutouts.setObjectName("cutouts")
        self.cutoutsLayout = QtWidgets.QGridLayout(self.cutouts)
        self.cutoutsLayout.setObjectName("cutoutsLayout")
        self.dummyWidget = QtWidgets.QWidget(self.cutouts)
        self.dummyWidget.setObjectName("dummyWidget")
        self.cutoutsLayout.addWidget(self.dummyWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.cutouts, 0, 0, 8, 5)
        self.widget_2 = QtWidgets.QWidget(self.mainframe)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 7, 5, 1, 1)
        self.widget = QtWidgets.QWidget(self.mainframe)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 9, 4, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.mainframe)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_2.addWidget(self.widget_9, 6, 5, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.mainframe)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_2.addWidget(self.widget_7, 5, 5, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.mainframe)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2.addWidget(self.widget_3, 9, 3, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.mainframe)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2.addWidget(self.widget_8, 3, 5, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.mainframe)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_2.addWidget(self.widget_5, 9, 5, 1, 1)
        self.buttonWidget = QtWidgets.QWidget(self.mainframe)
        self.buttonWidget.setMouseTracking(True)
        self.buttonWidget.setObjectName("buttonWidget")
        self.buttonsLayout = QtWidgets.QGridLayout(self.buttonWidget)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.helpButton = QtWidgets.QPushButton(self.buttonWidget)
        self.helpButton.setObjectName("helpButton")
        self.buttonsLayout.addWidget(self.helpButton, 1, 2, 1, 1)
        self.runGalfitButton = QtWidgets.QPushButton(self.buttonWidget)
        self.runGalfitButton.setObjectName("runGalfitButton")
        self.buttonsLayout.addWidget(self.runGalfitButton, 0, 2, 1, 1)
        self.quitButton = QtWidgets.QPushButton(self.buttonWidget)
        self.quitButton.setObjectName("quitButton")
        self.buttonsLayout.addWidget(self.quitButton, 1, 3, 1, 1)
        self.gridLayout_2.addWidget(self.buttonWidget, 11, 0, 1, 4)
        self.gridLayout.addWidget(self.mainframe, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.helpButton.setText(_translate("Form", "Help"))
        self.runGalfitButton.setText(_translate("Form", "Run galfit"))
        self.quitButton.setText(_translate("Form", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

