# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galfitWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(755, 615)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.mainframe = QtWidgets.QFrame(Form)
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainframe)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_23 = QtWidgets.QWidget(self.mainframe)
        self.widget_23.setObjectName("widget_23")
        self.gridLayout_2.addWidget(self.widget_23, 9, 11, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.mainframe)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_2.addWidget(self.widget_6, 0, 11, 1, 1)
        self.widget = QtWidgets.QWidget(self.mainframe)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 12, 10, 1, 1)
        self.widget_24 = QtWidgets.QWidget(self.mainframe)
        self.widget_24.setObjectName("widget_24")
        self.gridLayout_2.addWidget(self.widget_24, 11, 11, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.mainframe)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_2.addWidget(self.widget_7, 5, 11, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.mainframe)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2.addWidget(self.widget_3, 12, 9, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.mainframe)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 7, 11, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.mainframe)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_2.addWidget(self.widget_5, 12, 11, 1, 1)
        self.widget_17 = QtWidgets.QWidget(self.mainframe)
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_2.addWidget(self.widget_17, 12, 1, 1, 1)
        self.readoutframe = QtWidgets.QFrame(self.mainframe)
        self.readoutframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.readoutframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.readoutframe.setObjectName("readoutframe")
        self.readoutGridLayout = QtWidgets.QGridLayout(self.readoutframe)
        self.readoutGridLayout.setObjectName("readoutGridLayout")
        self.gridLayout_2.addWidget(self.readoutframe, 11, 0, 1, 11)
        self.widget_15 = QtWidgets.QWidget(self.mainframe)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_2.addWidget(self.widget_15, 2, 11, 1, 1)
        self.buttonWidget = QtWidgets.QWidget(self.mainframe)
        self.buttonWidget.setMouseTracking(True)
        self.buttonWidget.setObjectName("buttonWidget")
        self.buttonsLayout = QtWidgets.QGridLayout(self.buttonWidget)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.frame_3 = QtWidgets.QFrame(self.buttonWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.ycFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.ycFitLineEdit.setObjectName("ycFitLineEdit")
        self.gridLayout_4.addWidget(self.ycFitLineEdit, 3, 1, 1, 1)
        self.nFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.nFitLineEdit.setObjectName("nFitLineEdit")
        self.gridLayout_4.addWidget(self.nFitLineEdit, 3, 3, 1, 1)
        self.magFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.magFitLineEdit.setObjectName("magFitLineEdit")
        self.gridLayout_4.addWidget(self.magFitLineEdit, 4, 1, 1, 1)
        self.BAFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.BAFitLineEdit.setObjectName("BAFitLineEdit")
        self.gridLayout_4.addWidget(self.BAFitLineEdit, 5, 3, 1, 1)
        self.PAFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.PAFitLineEdit.setObjectName("PAFitLineEdit")
        self.gridLayout_4.addWidget(self.PAFitLineEdit, 4, 3, 1, 1)
        self.skyFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.skyFitLineEdit.setObjectName("skyFitLineEdit")
        self.gridLayout_4.addWidget(self.skyFitLineEdit, 5, 1, 1, 1)
        self.xcFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.xcFitLineEdit.setObjectName("xcFitLineEdit")
        self.gridLayout_4.addWidget(self.xcFitLineEdit, 2, 1, 1, 1)
        self.widget_21 = QtWidgets.QWidget(self.frame_3)
        self.widget_21.setObjectName("widget_21")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_21)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_16 = QtWidgets.QLabel(self.widget_21)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_21, 1, 0, 1, 4)
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 5, 0, 1, 1)
        self.ReFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.ReFitLineEdit.setObjectName("ReFitLineEdit")
        self.gridLayout_4.addWidget(self.ReFitLineEdit, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 5, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 4, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 4, 0, 1, 1)
        self.errorFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.errorFitLineEdit.setObjectName("errorFitLineEdit")
        self.gridLayout_4.addWidget(self.errorFitLineEdit, 6, 1, 1, 1)
        self.chiFitLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.chiFitLineEdit.setObjectName("chiFitLineEdit")
        self.gridLayout_4.addWidget(self.chiFitLineEdit, 6, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 6, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 6, 2, 1, 1)
        self.buttonsLayout.addWidget(self.frame_3, 0, 5, 1, 1)
        self.frame = QtWidgets.QFrame(self.buttonWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 2, 1, 1)
        self.BALineEdit = QtWidgets.QLineEdit(self.frame)
        self.BALineEdit.setObjectName("BALineEdit")
        self.gridLayout_3.addWidget(self.BALineEdit, 5, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 2, 1, 1)
        self.PALineEdit = QtWidgets.QLineEdit(self.frame)
        self.PALineEdit.setObjectName("PALineEdit")
        self.gridLayout_3.addWidget(self.PALineEdit, 4, 4, 1, 1)
        self.nLineEdit = QtWidgets.QLineEdit(self.frame)
        self.nLineEdit.setObjectName("nLineEdit")
        self.gridLayout_3.addWidget(self.nLineEdit, 3, 4, 1, 1)
        self.ReLineEdit = QtWidgets.QLineEdit(self.frame)
        self.ReLineEdit.setObjectName("ReLineEdit")
        self.gridLayout_3.addWidget(self.ReLineEdit, 2, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 2, 1, 1)
        self.widget_20 = QtWidgets.QWidget(self.frame)
        self.widget_20.setObjectName("widget_20")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(self.widget_20)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_20, 1, 0, 1, 5)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.xcLineEdit = QtWidgets.QLineEdit(self.frame)
        self.xcLineEdit.setObjectName("xcLineEdit")
        self.gridLayout_3.addWidget(self.xcLineEdit, 2, 1, 1, 1)
        self.ycLineEdit = QtWidgets.QLineEdit(self.frame)
        self.ycLineEdit.setObjectName("ycLineEdit")
        self.gridLayout_3.addWidget(self.ycLineEdit, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.magLineEdit = QtWidgets.QLineEdit(self.frame)
        self.magLineEdit.setObjectName("magLineEdit")
        self.gridLayout_3.addWidget(self.magLineEdit, 4, 1, 1, 1)
        self.buttonsLayout.addWidget(self.frame, 0, 4, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.buttonWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.runGalfitButton = QtWidgets.QPushButton(self.frame_2)
        self.runGalfitButton.setObjectName("runGalfitButton")
        self.verticalLayout.addWidget(self.runGalfitButton)
        self.helpButton = QtWidgets.QPushButton(self.frame_2)
        self.helpButton.setObjectName("helpButton")
        self.verticalLayout.addWidget(self.helpButton)
        self.quitButton = QtWidgets.QPushButton(self.frame_2)
        self.quitButton.setObjectName("quitButton")
        self.verticalLayout.addWidget(self.quitButton)
        self.buttonsLayout.addWidget(self.frame_2, 0, 2, 1, 2)
        self.gridLayout_2.addWidget(self.buttonWidget, 14, 0, 1, 11)
        self.widget_4 = QtWidgets.QWidget(self.mainframe)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2.addWidget(self.widget_4, 12, 3, 1, 1)
        self.widget_19 = QtWidgets.QWidget(self.mainframe)
        self.widget_19.setObjectName("widget_19")
        self.gridLayout_2.addWidget(self.widget_19, 12, 8, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.mainframe)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_2.addWidget(self.widget_13, 12, 6, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.mainframe)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_2.addWidget(self.widget_11, 12, 4, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.mainframe)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_2.addWidget(self.widget_9, 6, 11, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.mainframe)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_2.addWidget(self.widget_12, 12, 5, 1, 1)
        self.widget_22 = QtWidgets.QWidget(self.mainframe)
        self.widget_22.setObjectName("widget_22")
        self.gridLayout_2.addWidget(self.widget_22, 8, 11, 1, 1)
        self.widget_25 = QtWidgets.QWidget(self.mainframe)
        self.widget_25.setObjectName("widget_25")
        self.gridLayout_2.addWidget(self.widget_25, 10, 11, 1, 1)
        self.widget_18 = QtWidgets.QWidget(self.mainframe)
        self.widget_18.setObjectName("widget_18")
        self.gridLayout_2.addWidget(self.widget_18, 12, 7, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.mainframe)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2.addWidget(self.widget_8, 3, 11, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.mainframe)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_2.addWidget(self.widget_14, 1, 11, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.mainframe)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_2.addWidget(self.widget_10, 4, 11, 1, 1)
        self.widget_16 = QtWidgets.QWidget(self.mainframe)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_2.addWidget(self.widget_16, 12, 2, 1, 1)
        self.cutouts = QtWidgets.QFrame(self.mainframe)
        self.cutouts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cutouts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cutouts.setObjectName("cutouts")
        self.cutoutsLayout = QtWidgets.QGridLayout(self.cutouts)
        self.cutoutsLayout.setObjectName("cutoutsLayout")
        self.dummyWidget = QtWidgets.QWidget(self.cutouts)
        self.dummyWidget.setObjectName("dummyWidget")
        self.cutoutsLayout.addWidget(self.dummyWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.cutouts, 0, 0, 11, 11)
        self.gridLayout.addWidget(self.mainframe, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_10.setText(_translate("Form", "yc"))
        self.label_16.setText(_translate("Form", "FITTED PARAMETERS"))
        self.label_17.setText(_translate("Form", "sky"))
        self.label_9.setText(_translate("Form", "xc"))
        self.label_14.setText(_translate("Form", "Re"))
        self.label_15.setText(_translate("Form", "B/A"))
        self.label_12.setText(_translate("Form", "PA"))
        self.label_13.setText(_translate("Form", "n"))
        self.label_11.setText(_translate("Form", "mag"))
        self.label_18.setText(_translate("Form", "error"))
        self.label_19.setText(_translate("Form", "Chi"))
        self.label_6.setText(_translate("Form", "PA"))
        self.label_5.setText(_translate("Form", "n"))
        self.label_7.setText(_translate("Form", "B/A"))
        self.label_4.setText(_translate("Form", "Re"))
        self.label_8.setText(_translate("Form", "INITIAL PARAMETERS"))
        self.label.setText(_translate("Form", "xc"))
        self.label_2.setText(_translate("Form", "yc"))
        self.label_3.setText(_translate("Form", "mag"))
        self.runGalfitButton.setText(_translate("Form", "Run galfit"))
        self.helpButton.setText(_translate("Form", "Help"))
        self.quitButton.setText(_translate("Form", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

