# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'halphav3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 607)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainframe = QtWidgets.QFrame(self.centralwidget)
        self.mainframe.setMinimumSize(QtCore.QSize(503, 0))
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.leftLayout = QtWidgets.QGridLayout(self.mainframe)
        self.leftLayout.setObjectName("leftLayout")
        self.button_bar = QtWidgets.QWidget(self.mainframe)
        self.button_bar.setObjectName("button_bar")
        self.buttonLayout = QtWidgets.QGridLayout(self.button_bar)
        self.buttonLayout.setObjectName("buttonLayout")
        self.wfratio = QtWidgets.QPushButton(self.button_bar)
        self.wfratio.setObjectName("wfratio")
        self.buttonLayout.addWidget(self.wfratio, 0, 0, 1, 1)
        self.wgalid = QtWidgets.QComboBox(self.button_bar)
        self.wgalid.setObjectName("wgalid")
        self.buttonLayout.addWidget(self.wgalid, 0, 2, 1, 1)
        self.wclear = QtWidgets.QPushButton(self.button_bar)
        self.wclear.setObjectName("wclear")
        self.buttonLayout.addWidget(self.wclear, 0, 3, 1, 1)
        self.wmark = QtWidgets.QPushButton(self.button_bar)
        self.wmark.setObjectName("wmark")
        self.buttonLayout.addWidget(self.wmark, 0, 1, 1, 1)
        self.leftLayout.addWidget(self.button_bar, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.mainframe)
        self.rightFrame = QtWidgets.QFrame(self.centralwidget)
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.rightFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_7 = QtWidgets.QWidget(self.rightFrame)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout.addWidget(self.widget_7, 1, 0, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.rightFrame)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout.addWidget(self.widget_10, 6, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.rightFrame)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout.addWidget(self.widget_8, 3, 0, 1, 1)
        self.profiles = QtWidgets.QWidget(self.rightFrame)
        self.profiles.setObjectName("profiles")
        self.profilesLayout = QtWidgets.QGridLayout(self.profiles)
        self.profilesLayout.setObjectName("profilesLayout")
        self.widget_3 = QtWidgets.QWidget(self.profiles)
        self.widget_3.setObjectName("widget_3")
        self.profilesLayout.addWidget(self.widget_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.profiles, 5, 1, 2, 1)
        self.widget_9 = QtWidgets.QWidget(self.rightFrame)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout.addWidget(self.widget_9, 5, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.rightFrame)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout.addWidget(self.widget_6, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.rightFrame)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 1)
        self.cutouts = QtWidgets.QWidget(self.rightFrame)
        self.cutouts.setObjectName("cutouts")
        self.cutoutsLayout = QtWidgets.QGridLayout(self.cutouts)
        self.cutoutsLayout.setObjectName("cutoutsLayout")
        self.tempWidget = QtWidgets.QWidget(self.cutouts)
        self.tempWidget.setObjectName("tempWidget")
        self.cutoutsLayout.addWidget(self.tempWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.cutouts, 0, 1, 3, 1)
        self.rightButtons = QtWidgets.QWidget(self.rightFrame)
        self.rightButtons.setObjectName("rightButtons")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.rightButtons)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.profileButton = QtWidgets.QPushButton(self.rightButtons)
        self.profileButton.setObjectName("profileButton")
        self.gridLayout_4.addWidget(self.profileButton, 6, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.rightButtons)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 7, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.rightButtons)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ratioSliderLabel = QtWidgets.QLabel(self.frame)
        self.ratioSliderLabel.setObjectName("ratioSliderLabel")
        self.verticalLayout_2.addWidget(self.ratioSliderLabel, 0, QtCore.Qt.AlignHCenter)
        self.ratioSlider = QtWidgets.QSlider(self.frame)
        self.ratioSlider.setMouseTracking(True)
        self.ratioSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ratioSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ratioSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.ratioSlider.setObjectName("ratioSlider")
        self.verticalLayout_2.addWidget(self.ratioSlider)
        self.gridLayout_4.addWidget(self.frame, 0, 1, 1, 1)
        self.fluxButton = QtWidgets.QPushButton(self.rightButtons)
        self.fluxButton.setObjectName("fluxButton")
        self.gridLayout_4.addWidget(self.fluxButton, 6, 1, 1, 1)
        self.resetSizeButton = QtWidgets.QPushButton(self.rightButtons)
        self.resetSizeButton.setObjectName("resetSizeButton")
        self.gridLayout_4.addWidget(self.resetSizeButton, 4, 0, 1, 1)
        self.resetRatioButton = QtWidgets.QPushButton(self.rightButtons)
        self.resetRatioButton.setObjectName("resetRatioButton")
        self.gridLayout_4.addWidget(self.resetRatioButton, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.rightButtons)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 6, 0, 1, 1)
        self.prefixLineEdit = QtWidgets.QLineEdit(self.rightButtons)
        self.prefixLineEdit.setObjectName("prefixLineEdit")
        self.gridLayout_4.addWidget(self.prefixLineEdit, 7, 1, 1, 1)
        self.editMaskButton = QtWidgets.QPushButton(self.rightButtons)
        self.editMaskButton.setObjectName("editMaskButton")
        self.gridLayout_4.addWidget(self.editMaskButton, 7, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.rightButtons)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cutoutSliderLabel = QtWidgets.QLabel(self.frame_2)
        self.cutoutSliderLabel.setObjectName("cutoutSliderLabel")
        self.verticalLayout.addWidget(self.cutoutSliderLabel, 0, QtCore.Qt.AlignHCenter)
        self.cutoutSlider = QtWidgets.QSlider(self.frame_2)
        self.cutoutSlider.setOrientation(QtCore.Qt.Horizontal)
        self.cutoutSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.cutoutSlider.setObjectName("cutoutSlider")
        self.verticalLayout.addWidget(self.cutoutSlider)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        self.makeMaskButton = QtWidgets.QPushButton(self.rightButtons)
        self.makeMaskButton.setObjectName("makeMaskButton")
        self.gridLayout_4.addWidget(self.makeMaskButton, 0, 2, 1, 1)
        self.haTypeComboBox = QtWidgets.QComboBox(self.rightButtons)
        self.haTypeComboBox.setAutoFillBackground(False)
        self.haTypeComboBox.setCurrentText("")
        self.haTypeComboBox.setObjectName("haTypeComboBox")
        self.gridLayout_4.addWidget(self.haTypeComboBox, 4, 2, 1, 1)
        self.gridLayout.addWidget(self.rightButtons, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.rightFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 22))
        self.menubar.setObjectName("menubar")
        self.menuSetup = QtWidgets.QMenu(self.menubar)
        self.menuSetup.setObjectName("menuSetup")
        self.menuHalpha_Filter = QtWidgets.QMenu(self.menubar)
        self.menuHalpha_Filter.setObjectName("menuHalpha_Filter")
        MainWindow.setMenuBar(self.menubar)
        self.action_rcoadd = QtWidgets.QAction(MainWindow)
        self.action_rcoadd.setObjectName("action_rcoadd")
        self.action_hacoadd = QtWidgets.QAction(MainWindow)
        self.action_hacoadd.setObjectName("action_hacoadd")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.action_nsapath = QtWidgets.QAction(MainWindow)
        self.action_nsapath.setObjectName("action_nsapath")
        self.actionha4 = QtWidgets.QAction(MainWindow)
        self.actionha4.setObjectName("actionha4")
        self.actionha8 = QtWidgets.QAction(MainWindow)
        self.actionha8.setObjectName("actionha8")
        self.actionha12 = QtWidgets.QAction(MainWindow)
        self.actionha12.setObjectName("actionha12")
        self.actionha16 = QtWidgets.QAction(MainWindow)
        self.actionha16.setObjectName("actionha16")
        self.actionR_coadd = QtWidgets.QAction(MainWindow)
        self.actionR_coadd.setCheckable(False)
        self.actionR_coadd.setObjectName("actionR_coadd")
        self.actionHa_coadd = QtWidgets.QAction(MainWindow)
        self.actionHa_coadd.setObjectName("actionHa_coadd")
        self.actionHa_coadd_2 = QtWidgets.QAction(MainWindow)
        self.actionHa_coadd_2.setObjectName("actionHa_coadd_2")
        self.actionNSA_catalog_path = QtWidgets.QAction(MainWindow)
        self.actionNSA_catalog_path.setObjectName("actionNSA_catalog_path")
        self.actionQuit_2 = QtWidgets.QAction(MainWindow)
        self.actionQuit_2.setObjectName("actionQuit_2")
        self.actionhalpha4 = QtWidgets.QAction(MainWindow)
        self.actionhalpha4.setCheckable(True)
        self.actionhalpha4.setObjectName("actionhalpha4")
        self.actionhalpha8 = QtWidgets.QAction(MainWindow)
        self.actionhalpha8.setCheckable(True)
        self.actionhalpha8.setObjectName("actionhalpha8")
        self.actionhalpha12 = QtWidgets.QAction(MainWindow)
        self.actionhalpha12.setCheckable(True)
        self.actionhalpha12.setObjectName("actionhalpha12")
        self.actionhalpha16 = QtWidgets.QAction(MainWindow)
        self.actionhalpha16.setCheckable(True)
        self.actionhalpha16.setObjectName("actionhalpha16")
        self.menuSetup.addAction(self.actionR_coadd)
        self.menuSetup.addAction(self.actionHa_coadd_2)
        self.menuSetup.addAction(self.actionNSA_catalog_path)
        self.menuSetup.addSeparator()
        self.menuSetup.addAction(self.actionQuit_2)
        self.menuHalpha_Filter.addAction(self.actionhalpha4)
        self.menuHalpha_Filter.addAction(self.actionhalpha8)
        self.menuHalpha_Filter.addAction(self.actionhalpha12)
        self.menuHalpha_Filter.addAction(self.actionhalpha16)
        self.menubar.addAction(self.menuSetup.menuAction())
        self.menubar.addAction(self.menuHalpha_Filter.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.wfratio.setText(_translate("MainWindow", "Get Filter Ratio"))
        self.wclear.setText(_translate("MainWindow", "Clear Canvas"))
        self.wmark.setText(_translate("MainWindow", "Find Galaxies"))
        self.widget_3.setToolTip(_translate("MainWindow", "HalphaType"))
        self.profileButton.setText(_translate("MainWindow", "Plot Profiles"))
        self.label.setText(_translate("MainWindow", "Output Prefix"))
        self.ratioSliderLabel.setText(_translate("MainWindow", "filter ratio"))
        self.fluxButton.setText(_translate("MainWindow", "Measure Flux"))
        self.resetSizeButton.setText(_translate("MainWindow", "Reset Cutout Size"))
        self.resetRatioButton.setText(_translate("MainWindow", "Reset Filter Ratio"))
        self.pushButton.setText(_translate("MainWindow", "Fit Ellipse"))
        self.editMaskButton.setText(_translate("MainWindow", "Save Galaxy"))
        self.cutoutSliderLabel.setText(_translate("MainWindow", "cutout size"))
        self.makeMaskButton.setText(_translate("MainWindow", "Make and Edit Mask"))
        self.haTypeComboBox.setToolTip(_translate("MainWindow", "HalphaType"))
        self.menuSetup.setTitle(_translate("MainWindow", "Setup"))
        self.menuHalpha_Filter.setTitle(_translate("MainWindow", "Halpha Filter"))
        self.action_rcoadd.setText(_translate("MainWindow", "R-band coadd"))
        self.action_hacoadd.setText(_translate("MainWindow", "Halpha coadd"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.action_nsapath.setText(_translate("MainWindow", "set_path"))
        self.actionha4.setText(_translate("MainWindow", "ha4"))
        self.actionha8.setText(_translate("MainWindow", "ha8"))
        self.actionha12.setText(_translate("MainWindow", "ha12"))
        self.actionha16.setText(_translate("MainWindow", "ha16"))
        self.actionR_coadd.setText(_translate("MainWindow", "R coadd path"))
        self.actionR_coadd.setStatusTip(_translate("MainWindow", "full path of R-band coadded image"))
        self.actionHa_coadd.setText(_translate("MainWindow", "Ha coadd path"))
        self.actionHa_coadd.setWhatsThis(_translate("MainWindow", "full path to Halpha coadd image"))
        self.actionHa_coadd_2.setText(_translate("MainWindow", "Ha coadd path"))
        self.actionHa_coadd_2.setStatusTip(_translate("MainWindow", "select Halpha coadded image"))
        self.actionNSA_catalog_path.setText(_translate("MainWindow", "NSA catalog path"))
        self.actionQuit_2.setText(_translate("MainWindow", "Quit"))
        self.actionhalpha4.setText(_translate("MainWindow", "halpha4"))
        self.actionhalpha8.setText(_translate("MainWindow", "halpha8"))
        self.actionhalpha12.setText(_translate("MainWindow", "halpha12"))
        self.actionhalpha16.setText(_translate("MainWindow", "halpha16"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

