# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maskWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(665, 555)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.mainframe = QtWidgets.QFrame(Form)
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainframe)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.mainframe)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2.addWidget(self.widget_3, 9, 5, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.mainframe)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_2.addWidget(self.widget_10, 4, 12, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.mainframe)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2.addWidget(self.widget_4, 9, 4, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.mainframe)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_2.addWidget(self.widget_11, 9, 2, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.mainframe)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_2.addWidget(self.widget_9, 6, 12, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.mainframe)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 7, 12, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.mainframe)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_2.addWidget(self.widget_14, 1, 12, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.mainframe)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_2.addWidget(self.widget_7, 5, 12, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.mainframe)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_2.addWidget(self.widget_13, 9, 1, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.mainframe)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2.addWidget(self.widget_8, 3, 12, 1, 1)
        self.widget = QtWidgets.QWidget(self.mainframe)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 9, 7, 1, 1)
        self.widget_20 = QtWidgets.QWidget(self.mainframe)
        self.widget_20.setObjectName("widget_20")
        self.gridLayout_2.addWidget(self.widget_20, 9, 9, 1, 1)
        self.widget_15 = QtWidgets.QWidget(self.mainframe)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_2.addWidget(self.widget_15, 2, 12, 1, 1)
        self.cutouts = QtWidgets.QFrame(self.mainframe)
        self.cutouts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cutouts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cutouts.setObjectName("cutouts")
        self.cutoutsLayout = QtWidgets.QGridLayout(self.cutouts)
        self.cutoutsLayout.setObjectName("cutoutsLayout")
        self.dummyWidget = QtWidgets.QWidget(self.cutouts)
        self.dummyWidget.setObjectName("dummyWidget")
        self.cutoutsLayout.addWidget(self.dummyWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.cutouts, 0, 1, 8, 11)
        self.widget_5 = QtWidgets.QWidget(self.mainframe)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_2.addWidget(self.widget_5, 9, 12, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.mainframe)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_2.addWidget(self.widget_12, 9, 3, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.mainframe)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_2.addWidget(self.widget_6, 0, 12, 1, 1)
        self.widget_19 = QtWidgets.QWidget(self.mainframe)
        self.widget_19.setObjectName("widget_19")
        self.gridLayout_2.addWidget(self.widget_19, 9, 6, 1, 1)
        self.widget_17 = QtWidgets.QWidget(self.mainframe)
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_2.addWidget(self.widget_17, 9, 10, 1, 1)
        self.widget_18 = QtWidgets.QWidget(self.mainframe)
        self.widget_18.setObjectName("widget_18")
        self.gridLayout_2.addWidget(self.widget_18, 9, 8, 1, 1)
        self.widget_16 = QtWidgets.QWidget(self.mainframe)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_2.addWidget(self.widget_16, 9, 11, 1, 1)
        self.readoutframe = QtWidgets.QFrame(self.mainframe)
        self.readoutframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.readoutframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.readoutframe.setObjectName("readoutframe")
        self.readoutGridLayout = QtWidgets.QGridLayout(self.readoutframe)
        self.readoutGridLayout.setObjectName("readoutGridLayout")
        self.gridLayout_2.addWidget(self.readoutframe, 8, 1, 1, 11)
        self.buttonWidget = QtWidgets.QWidget(self.mainframe)
        self.buttonWidget.setMouseTracking(True)
        self.buttonWidget.setObjectName("buttonWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.buttonWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.seThresholdLineEdit = QtWidgets.QLineEdit(self.buttonWidget)
        self.seThresholdLineEdit.setObjectName("seThresholdLineEdit")
        self.gridLayout_3.addWidget(self.seThresholdLineEdit, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.buttonWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.buttonWidget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 1, 1, 1)
        self.mhelpButton = QtWidgets.QPushButton(self.buttonWidget)
        self.mhelpButton.setObjectName("mhelpButton")
        self.gridLayout_3.addWidget(self.mhelpButton, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.buttonWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 1, 1, 1)
        self.seSNRLineEdit = QtWidgets.QLineEdit(self.buttonWidget)
        self.seSNRLineEdit.setObjectName("seSNRLineEdit")
        self.gridLayout_3.addWidget(self.seSNRLineEdit, 2, 2, 1, 1)
        self.mquitButton = QtWidgets.QPushButton(self.buttonWidget)
        self.mquitButton.setObjectName("mquitButton")
        self.gridLayout_3.addWidget(self.mquitButton, 1, 3, 1, 1)
        self.boxSizeLineEdit = QtWidgets.QLineEdit(self.buttonWidget)
        self.boxSizeLineEdit.setObjectName("boxSizeLineEdit")
        self.gridLayout_3.addWidget(self.boxSizeLineEdit, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.buttonWidget, 10, 1, 2, 11)
        self.gridLayout.addWidget(self.mainframe, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Box Size"))
        self.label.setText(_translate("Form", "SE threshold (0=lots, 1=no deblend, def 0.05)"))
        self.mhelpButton.setText(_translate("Form", "Help          "))
        self.label_2.setText(_translate("Form", "SE SNR (default=2)"))
        self.mquitButton.setText(_translate("Form", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

